"""Recording-time driver. Everything S1..S5 shows on screen and says
into the operator's headphones comes from here -- no keys touched
after this starts, until S6 (browser, still manual).

    python -m scripts.demo_recorder.player --test 5     # gate check, see docs/RECORDING.md step 0
    python -m scripts.demo_recorder.player              # full take: opens screencapture itself
    python -m scripts.demo_recorder.player --dry-run     # print the timeline, touch nothing
    python -m scripts.demo_recorder.player --segment S2 --calibrate  # tune one segment's beats
    python -m scripts.demo_recorder.player --from S3      # re-take from a segment onward
    python -m scripts.demo_recorder.player --no-capture   # QuickTime fallback, no screencapture
"""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

from .common import ROOT, TAKES, SEGMENTS, note, load_config
from .logs import parse as parse_batch_log
from .scenes import SCENES

ORDER = ["S1", "S2", "S3", "S4", "S5"]
DISPLAY = 1
LEAD_IN = 3.0
S6_BUDGET = 45.0  # manual browser beats + end card + 2s hold; tune after a real S6 pass


def segment_mp3(seg: str) -> Path:
    return SEGMENTS / f"{seg}.mp3"


def afinfo_duration(path: Path) -> float:
    out = subprocess.run(["afinfo", str(path)], capture_output=True, text=True).stdout
    for line in out.splitlines():
        if "estimated duration" in line:
            return float(line.split(":")[1].strip().split()[0])
    raise RuntimeError(f"could not read duration from afinfo {path}")


def durations() -> dict[str, float]:
    return {seg: afinfo_duration(segment_mp3(seg)) for seg in ORDER + ["S6"]}


def play_narration(seg: str) -> subprocess.Popen:
    return subprocess.Popen(["afplay", str(segment_mp3(seg))],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def cmd_test(seconds: int) -> None:
    out = TAKES / "test.mov"
    note(f"recording {seconds}s test clip to {out}")
    proc = subprocess.Popen(
        ["screencapture", "-v", "-V", str(seconds), "-C", "-x", "-D", str(DISPLAY), str(out)])
    time.sleep(0.5)
    print()
    print("\033[7m REVERSE-VIDEO SAMPLE -- confirm this survives in the clip \033[0m")
    print("\033[36mcyan\033[0m \033[32mgreen\033[0m plain")
    proc.wait()
    note(f"done -- open {out} and check: permission dialog absent, cursor visible, "
         "colors intact, no audio track. If any of those fail, use --no-capture.")


def cmd_dry_run() -> None:
    d = durations()
    total = LEAD_IN + sum(d[s] for s in ORDER) + S6_BUDGET
    for seg in ORDER:
        print(f"{seg}: {d[seg]:6.1f}s")
    print(f"S6 (manual budget): {S6_BUDGET:6.1f}s (mp3 is {d['S6']:.1f}s)")
    print(f"lead-in:            {LEAD_IN:6.1f}s")
    print(f"TOTAL:              {total:6.1f}s  ({total/60:.2f} min)")
    if total > 240:
        note("WARNING: total exceeds the 4:00 cap -- trim S6_BUDGET or a scene")


def cmd_calibrate(seg: str) -> None:
    dur = afinfo_duration(segment_mp3(seg))
    note(f"playing {seg}.mp3 ({dur:.1f}s) with a 1s ticker -- "
         "note the second where each beat should land, then edit "
         f"scenes.py's {seg}_ORIG dict")
    proc = play_narration(seg)
    t0 = time.monotonic()
    while proc.poll() is None:
        elapsed = time.monotonic() - t0
        print(f"\r{elapsed:5.1f}s", end="", flush=True)
        time.sleep(0.1)
    print()


def cmd_segment(seg: str, cfg: dict, blog) -> None:
    from .common import Clock
    dur = afinfo_duration(segment_mp3(seg))
    proc = play_narration(seg)
    clock = Clock()
    SCENES[seg](cfg, blog, clock, dur)
    proc.wait()


def write_mux_script(timeline: dict[str, float], video_path: Path) -> Path:
    mux_path = TAKES / "mux.sh"
    inputs = " ".join(f'-i "{segment_mp3(s)}"' for s in ORDER + ["S6"])
    filters = []
    labels = []
    for i, seg in enumerate(ORDER + ["S6"], start=1):
        ms = round(timeline.get(seg, 0.0) * 1000)
        filters.append(f"[{i}:a]adelay={ms}|{ms}[a{i}]")
        labels.append(f"[a{i}]")
    filter_complex = ";".join(filters) + f";{''.join(labels)}amix=inputs={len(labels)}:normalize=0[aout]"
    out_path = TAKES / "final.mov"
    script = f"""#!/bin/bash
# Generated by scripts/demo_recorder/player.py -- do not hand-edit the
# adelay offsets, re-run player.py instead so mux.sh stays truthful to
# take-timeline.json.
set -euo pipefail
cd "{ROOT}"
ffmpeg -y -i "{video_path}" {inputs} -filter_complex "{filter_complex}" \\
  -map 0:v -map "[aout]" -c:v copy -shortest "{out_path}"
echo "wrote {out_path}"
"""
    mux_path.write_text(script)
    mux_path.chmod(0o755)
    return mux_path


def cmd_full(*, from_segment: str | None, no_capture: bool) -> None:
    cfg = load_config()
    blog = parse_batch_log(TAKES / "batch.log")
    d = durations()

    start_idx = ORDER.index(from_segment) if from_segment else 0
    segments = ORDER[start_idx:]

    video_path = TAKES / "take.mov"
    total_budget = LEAD_IN + sum(d[s] for s in segments) + S6_BUDGET + 20

    capture_proc = None
    if not no_capture:
        note(f"starting screencapture, budget {total_budget:.0f}s -> {video_path}")
        capture_proc = subprocess.Popen(
            ["screencapture", "-v", "-V", str(int(total_budget)), "-C", "-x",
             "-D", str(DISPLAY), str(video_path)])
    else:
        note("recording is on you -- start QuickTime now")
        input("press Enter once QuickTime is recording... ")

    time.sleep(LEAD_IN)
    rec_t0 = time.monotonic()
    timeline: dict[str, float] = {s: None for s in ORDER}

    for seg in segments:
        timeline[seg] = time.monotonic() - rec_t0
        note(f"segment {seg} at t={timeline[seg]:.1f}s (mp3 {d[seg]:.1f}s)")
        from .common import Clock
        proc = play_narration(seg)
        clock = Clock()
        SCENES[seg](cfg, blog, clock, d[seg])
        clock.wait_until(d[seg])
        proc.wait()

    note("S1..S5 done. Manual S6 now: agent card tab, Logs Explorer tab, "
         "highlight the six span attributes, end card. See docs/RECORDING.md Part 2 step 5.")
    input("press Enter the instant you switch to the browser for S6... ")
    timeline["S6"] = time.monotonic() - rec_t0

    if capture_proc is not None:
        note("waiting for screencapture's own -V timer to stop the recording")
        capture_proc.wait()
    else:
        input("press Enter after you've stopped QuickTime... ")

    timeline["_video_start_offset"] = 0.0
    TAKES.mkdir(parents=True, exist_ok=True)
    (TAKES / "take-timeline.json").write_text(json.dumps(timeline, indent=2))
    note(f"wrote {TAKES / 'take-timeline.json'}")

    mux_path = write_mux_script(timeline, video_path)
    note(f"wrote {mux_path} -- run it once ffmpeg is ready: bash {mux_path}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--test", type=int, metavar="SECONDS")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--segment", metavar="S1..S5")
    ap.add_argument("--calibrate", action="store_true")
    ap.add_argument("--from", dest="from_segment", metavar="S1..S5")
    ap.add_argument("--no-capture", action="store_true")
    args = ap.parse_args()

    if args.test is not None:
        cmd_test(args.test)
        return
    if args.dry_run:
        cmd_dry_run()
        return
    if args.segment and args.calibrate:
        cmd_calibrate(args.segment)
        return
    if args.segment:
        cfg = load_config()
        blog = parse_batch_log(TAKES / "batch.log")
        cmd_segment(args.segment, cfg, blog)
        return

    cmd_full(from_segment=args.from_segment, no_capture=args.no_capture)


if __name__ == "__main__":
    main()
